exclude: (data/|README.md)
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3.9
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
  - repo: https://github.com/kadrach/pre-commit-gitlabci-lint
    rev: 22d0495c9894e8b27cc37c2ed5d9a6b46385a44c
    hooks:
      - id: gitlabci-lint
        args: ["https://gitlab.littlerocket.team"]
#  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
#    rev: v2.2.0
#   hooks:
#     - id: commitlint
#       stages: [ commit-msg ]
#       additional_dependencies: [ '@commitlint/config-conventional' ]
